# Generated by Django 2.2.24 on 2025-02-05 17:44

from django.db import migrations

def fill_new_building(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')  # Замените 'property' на имя вашего приложения
    for flat in Flat.objects.all():
        if flat.construction_year and flat.construction_year >= 2015:
            flat.new_building = True
        else:
            flat.new_building = False
        flat.save()

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_flat_new_building'),  # Укажите правильный файл предыдущей миграции
    ]

    operations = [
        migrations.RunPython(fill_new_building),
    ]

